### ISSUE TITLE
Create Socket-based Messaging prototype

### ISSUE THREAD

**Issue by TerrenceHo** [ucladevx/UCLAEats-backend#3]
Implement socket-based messaging in Django

**Comment by alexcyun** [comment]
In Order of TODO
* Hash unique URL to create "chat-room" for each user
* Emit messages directed to specific users
* Security Protocols to ensure users are correct
* Integrate with any socket based messaging, particularly iOS
* Dockerize messaging app

**Comment by HirdayGupta** [comment]
Pretty sure this is closed with work done by @JayantMehra
