### ISSUE TITLE
Create new chats endpoint

### ISSUE THREAD

**Issue by HirdayGupta** [ucladevx/UCLAEats-backend#30]
New route: `api/v1/users/matching/chats` with GET param user `"id"`

This should return data in the exact same format as `GET api/v1/users/matching/matches` (and accept the exact same parameters) - but instead of returning all successful matches, it filters its response and returns only the **closest upcoming match-time** for each pair of users. (To avoid duplicate chat rooms, as discussed in meetings).

**What does closest upcoming match-time mean?**
If the same two users match repeatedly (which is bound to happen when we have very few users for the first few months), then the `matching/chats` endpoint being created here should return the first upcoming match row for the two users. 

* Meaning if the two users have two successful matches - one tomorrow and one two days from now, return the row which has tomorrow's match details. 
* If the two users have successfully matched in the past but there's no upcoming match dates, then return the row with the most recent match date.

All of these considerations are only for the cases when a given pair of users matches more than once - if they only match once - just return the row their match corresponds to, plain and simple. 

Note that this new endpoint IS NOT replacing the old one, it is going to co-exist, in addition to it.

**Comment by shangyuhsu** [comment]
change made to n2/matching-api
